# Discord bot block settings
bot:
  token: ''
  command-prefix: '$'

# Database block settings
db-settings:
  driver: 'mysql'       # Database driver (mysql, psql, etc.)
  username: ''          # Database username
  password: ''          # Database user password
  port: 3306            # Database port (Default: 3306)
  host: 'localhost'     # Database host (Default: localhost)
  database: ''          # Database name

# Debug Mode (true/false)
debug: false

# Development mode (true/false)
development: false

# Optional block
users:
  - username

# Optional block
SpideyBot:
  branch: branch-name
  color: test-result-color
  channel: 'channel'


