@startuml
scale 1
' skinparam classAttributeIconSize 0

interface IAddress
{
    + String Address 
}
interface IAddressee
{
    + String Addressee
} 

interface IMailAddress
{
}

interface IHeader
{
    + String Header 
}
interface IMessage
{
    + JSON Message
}

interface IMail
{
}

interface IMailHandler
{
}
interface IMailSender
{
    - IPostSender PostSender
    + void Init(IPostSender)
    + void Send(IPostSender)
}
interface IPostSender
{
    + void Init()
    + void Send(IMailAddress)
}


interface IMailReceiver
{
    + void Receive(IMailAddress)
}
interface IPostReceiver
{
    + IMailReceiver MailReceiver
    + void Init(IMailReceiver)
    + void Received(IMailAddress)
}

interface IPostHandler
{
}

IMessage <|-- IMailAddress
IHeader <|-- IMailAddress
IAddressee <|-- IMailAddress
IAddress <|-- IMailAddress

IMailHandler <|-- IMailReceiver
IMailHandler <|-- IMailSender

IMailSender ..> IMailAddress
IMailReceiver ..> IMailAddress
IMailAddress <-- IPostSender
IMailAddress <.. IPostReceiver

IMailSender --o IPostSender
IMailReceiver o-- IPostReceiver

IPostReceiver --|> IPostHandler
IPostSender  --|> IPostHandler

@enduml